# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=500)),
                ('info_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
